config/routes.rb
PscAdmin::Application.routes.draw do

  match 'auth/:provider/callback', :controller => :sessions, :action => :create
  match 'sign_in',                 :controller => :sessions, :action => :new,     :as => :sign_in
  match 'sign_out',                :controller => :sessions, :action => :destroy, :as => :sign_out

  resources :admins, :except => [ :new ]
  resources :concert_series
  resources :concerts
  resources :members do
    resources :subscriptions
  end

  root :to => 'members#index'
end

app/views/admins/_form.html.erb
<%= simple_form_for(admin, :html => { :class => 'form-horizontal'} ) do |f| %>
  <%= f.error_notification %>

  <div class='form-inputs'>
    <%= f.input :name, :wrapper => :prepend do %>
      <%= content_tag(:span, icon(:user), :class => 'add-on') %>
      <%= f.input_field :name %>
    <% end -%>
  </div>

  <div class='form-actions'>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing <%= @admin.name -%></h1>

<%= render 'form', :admin => @admin %>

<% content_for :actions do -%>
  <li><%= link_to 'Back', admins_path %></li>
<% end -%>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table class='table table-hover table-striped'>
  <thead>
    <tr>
      <th> Name </th>
      <th> Email </th>
      <th> Status </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @admins.each do |admin| %>
    <tr id='<%= element_id(admin) -%>'>
      <td><%= link_to admin.name, edit_admin_path(admin) %></td>
      <td><%= admin.email %></td>
      <td><%= admin.active? ? 'Active' : 'Inactive' %></td>
      <td>
        <% if current_admin.id == admin.id -%>
          &nbsp;
        <% else -%>
          <% if admin.active? -%>
            <%= link_to 'Deactivate', admin, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
          <% else -%>
            <%= link_to 'Reactivate', admin_path(admin, :admin => { :active => true }), :method => :put %>
          <% end -%>
        <% end -%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for :actions do -%>
  <li><%= link_to 'Edit', edit_admin_path(@admin) %></li>
  <li><%= link_to 'Back', admins_path %></li>
<% end -%>