config/routes.rb
PscAdmin::Application.routes.draw do

  match 'auth/:provider/callback', :controller => :sessions, :action => :create
  match 'sign_in',                 :controller => :sessions, :action => :new,     :as => :sign_in
  match 'sign_out',                :controller => :sessions, :action => :destroy, :as => :sign_out

  resources :admins, :except => [ :new ]
  resources :concert_series
  resources :concerts
  resources :members do
    resources :subscriptions
  end

  root :to => 'members#index'
end

app/models/subscription.rb
class Subscription
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :member
  belongs_to :concert_series

  field :quantity, :type => Integer
  field :reserved, :type => Boolean
  field :seat_or_ticket_number

  validates :seat_or_ticket_number, :presence  => true
  validates :quantity, :numericality => { :greater_than => 0 }

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def index
    @member        = Member.find(params[:member_id])
    @subscriptions = @member.subscriptions
  end

  def new
    @member       = Member.find(params[:member_id])
    @subscription = @member.subscriptions.new
  end

  def create
    @member       = Member.find(params[:member_id])
    @subscription = @member.subscriptions.build(params[:subscription])
    if @subscription.save
      flash.keep.notice = "#{@member.full_name} is subscribed to #{@subscription.concert_series.name}"
      redirect_to :action => :index
    else
    end
  end


  private

  def set_tab
    @tab = 'members'
  end
end

app/views/subscriptions/_form.html.erb
<%= simple_form_for([member, subscription], :html => { :class => 'form-horizontal'} ) do |f| %>
  <%= f.error_notification %>

  <div class='form-inputs'>

    <%= f.association :concert_series,
      :collection   => ConcertSeries.all.to_a,
      :label_method => :name,
      :value_method => :id,
      :prompt => 'Select a Concert Series' %>

    <%= f.input :reserved, :wrapper => :prepend do %>
      <%= f.check_box :reserved %>
    <% end -%>

    <%= f.input :quantity, :wrapper => :prepend do %>
      <%= content_tag(:span, '#', :class => 'add-on') %>
      <%= f.input_field :quantity %>
    <% end -%>

    <%= f.input :seat_or_ticket_number , :wrapper => :prepend do %>
      <%= content_tag(:span, '#', :class => 'add-on') %>
      <%= f.input_field :seat_or_ticket_number   %>
    <% end -%>
  </div>

  <div class='form-actions'>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subscriptions/index.html.erb
<h1><%= @member.full_name %></h1>

<ul class='nav nav-tabs'>
  <li class='active'>
  <%= link_to('Subscriptions', member_subscriptions_path(@member)) -%>
  </li>
</ul>

<div class='tab-content'>
  <div class='tab-pane active'>
    <table class='table table-hover table-striped'>
      <thead>
        <tr>
          <th> Concert Series </th>
          <th> Quantity </th>
          <th> Seat or ticket number </th>
        </tr>
      </thead>

      <tbody>
      <% @subscriptions.each do |subscription| %>
        <tr id='<%= element_id(subscription) -%>'>
          <td><%= subscription.concert_series.name %></td>
          <td><%= subscription.quantity %></td>
          <td><%= subscription.seat_or_ticket_number %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<% content_for :actions do -%>
  <li><%= link_to 'Edit', edit_member_path(@member) %></li>
  <li><%= link_to 'Back', members_path %></li>
<% end -%>

<% content_for :subnav do -%>
  <li class='nav-header'>Subscriptions</li>
  <li><%= link_to 'New Subscription', new_member_subscription_path(@member) %></li>
<% end -%>

app/views/subscriptions/new.html.erb
<h1><%= @member.full_name %></h1>

<ul class='nav nav-tabs'>
  <li class='active'>
    <%= link_to('Subscriptions', member_subscriptions_path(@member)) -%>
  </li>
</ul>

<div class='tab-content'>
  <div class='tab-pane active'>
    <%= render 'form', :member => @member, :subscription => @subscription %>
  </div>
</div>

<% content_for :actions do -%>
  <li><%= link_to 'Edit', edit_member_path(@member) %></li>
  <li><%= link_to 'Back', members_path %></li>
<% end -%>

<% content_for :subnav do -%>
  <li class='nav-header'>Subscriptions</li>
<% end -%>