config/routes.rb
PscAdmin::Application.routes.draw do

  match 'auth/:provider/callback', :controller => :sessions, :action => :create
  match 'sign_in',                 :controller => :sessions, :action => :new,     :as => :sign_in
  match 'sign_out',                :controller => :sessions, :action => :destroy, :as => :sign_out

  resources :admins, :except => [ :new ]
  resources :concert_series
  resources :concerts
  resources :members do
    resources :subscriptions
  end

  root :to => 'members#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Peoples' Symphony Concerts Administraive Tool" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'PSC Admin Tool', root_path, :class => 'brand' -%>
          <div class="container-fluid nav-collapse">
            <%= admin_only do -%>
              <ul class="nav">
                <li class="<%= 'active' if @tab.to_s == 'admins'         %>"> <%= link_to 'Admins',         admins_path -%>               </li>
                <li class="<%= 'active' if @tab.to_s == 'members'        %>"> <%= link_to 'Members',        members_path -%>              </li>
                <li class="<%= 'active' if @tab.to_s == 'concert_series' %>"> <%= link_to 'Concert Series', concert_series_index_path -%> </li>
                <li class="<%= 'active' if @tab.to_s == 'concerts'       %>"> <%= link_to 'Concerts',       concerts_path -%>             </li>
              </ul>
            <% end -%>

            <ul class="nav pull-right">
              <% if current_admin -%>
                <li>
                  <p class="navbar-text">
                    <%= current_admin.name -%>
                  </p>
                </li>
                <li>
                  <%= link_to sign_out_path, :method => :delete, :id =>'signout' do -%>
                    Logout <%= icon(:signout) %>
                  <% end -%>
                </li>
              <% else -%>
                <li>
                  <%= link_to '/auth/google_apps' do %>
                    Login <%= content_tag(:span, icon('google-plus')) %>
                  <% end -%>
                </li>
              <% end -%>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <% if content_for?(:actions) %>
                <li class="nav-header">Actions</li>
                <%= yield :actions %>
              <% end %>

              <% if content_for?(:subnav) %>
                <%= yield :subnav %>
              <% end %>

            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <div id='footer'>
        <div class='container'>
          <p>&copy; Peoples' Symphony Concerts Admin Database 2013</p>
        </div>
      </div>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>