config/routes.rb
PscAdmin::Application.routes.draw do

  match 'auth/:provider/callback', :controller => :sessions, :action => :create
  match 'sign_in',                 :controller => :sessions, :action => :new,     :as => :sign_in
  match 'sign_out',                :controller => :sessions, :action => :destroy, :as => :sign_out

  resources :admins, :except => [ :new ]
  resources :concert_series
  resources :concerts
  resources :members do
    resources :subscriptions
  end

  root :to => 'members#index'
end

app/models/member.rb
class Member
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :subscriptions

  SOURCES = %w{ brochure concert online renewal }

  field :first_name
  field :last_name
  field :address1
  field :address2
  field :city
  field :state
  field :zip_code
  field :state
  field :primary_phone
  field :secondary_phone
  field :email
  field :source
  field :received_at,  :type => Date
  field :mailing_list, :type => Boolean

  validates :first_name,      :presence  => true
  validates :last_name,       :presence  => true
  validates :address1,        :presence  => true, :if => :address2?
  validates :email,           :presence  => true, :if => :mailing_list?

  validates :zip_code,        :format => { :with => /^\d{5}-?\d{4}?$/,     :message => 'should be formatted like ##### or #####-####',                       :allow_blank => true }
  validates :primary_phone,   :format => { :with => /^\d{3}-\d{3}-\d{4}$/, :message => 'please enter the phone number in the following format ###-###-####', :allow_blank => true }
  validates :secondary_phone, :format => { :with => /^\d{3}-\d{3}-\d{4}$/, :message => 'please enter the phone number in the following format ###-###-####', :allow_blank => true }
  validates :email,           :format => { :with => /.+@.+\..+/,           :message => 'please enter an email address like handle@domain.net',               :allow_blank => true }

  validates :email, :uniqueness => true, :allow_blank => true

  validates :state,           :inclusion => { :in => PscVariables::STATES.values.map{|h|h['abbreviation']}, :allow_blank => true }
  validates :source,          :inclusion => { :in => SOURCES,                                               :allow_blank => true }

  before_validation :format_primary_phone,   :if => :primary_phone?
  before_validation :format_secondary_phone, :if => :secondary_phone?

  def full_name
    [first_name, last_name].join(' ')
  end

  private

  def format_primary_phone
    format_phone(:primary_phone)
  end

  def format_secondary_phone
    format_phone(:secondary_phone)
  end

  def format_phone(field)
    phone = send(field)
    phone = phone.gsub(/\D*/,'')
    phone = [ phone.slice(0,3), phone.slice(3,3), phone.slice(6,4) ].join('-')
    send("#{field}=", phone)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    @members = Member.page(params[:page] || 1)
    if @query = params[:query]
      regex = /#{@query}/i
      @members = @members.or([{ :first_name => regex },
                              { :last_name  => regex },
                              { :email      => regex }])
    end
    flash.alert = 'No Members Found' if @members.none?
    @members
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def edit
    @member = Member.find(params[:id])
  end

  def create
    @member = Member.new(params[:member])

    if @member.save
      flash.keep.notice = "#{@member.full_name} was successfully created."
      redirect_to action: :index
    else
      render action: 'new'
    end
  end

  def update
    @member = Member.find(params[:id])

    if @member.update_attributes(params[:member])
      flash.keep.notice = "Successfully updated #{@member.full_name}"
      redirect_to action: :index
    else
      render action: 'edit'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    redirect_to members_url
  end

  private

  def set_tab
    @tab = 'members'
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= simple_form_for(member, :html => { :class => 'form-horizontal'} ) do |f| %>
  <%= f.error_notification %>

  <div class='form-inputs'>
    <%= f.input :first_name, :wrapper => :prepend do %>
      <%= content_tag(:span, 'F', :class => 'add-on') %>
      <%= f.input_field :first_name %>
    <% end -%>

    <%= f.input :last_name, :wrapper => :prepend do %>
      <%= content_tag(:span, 'L', :class => 'add-on') %>
      <%= f.input_field :last_name %>
    <% end -%>

    <%= f.input :email, :wrapper => :prepend do %>
      <%= content_tag(:span, '@', :class => 'add-on') %>
      <%= f.input_field :email %>
    <% end -%>

    <%= f.input :mailing_list, :wrapper => :prepend do %>
      <%= f.check_box :mailing_list %>
    <% end -%>

    <%= f.input :primary_phone, :wrapper => :prepend do %>
      <%= content_tag(:span, icon(:mobile_phone), :class => 'add-on') %>
      <%= f.input_field :primary_phone %>
    <% end -%>

    <%= f.input :secondary_phone , :wrapper => :prepend do %>
      <%= content_tag(:span, icon(:mobile_phone), :class => 'add-on') %>
      <%= f.input_field :secondary_phone  %>
    <% end -%>

    <% collection = Member::SOURCES.map{ |source| [ source.titleize, source ] } %>
    <%= f.input :source, :prompt => 'Please select a source', :wrapper => :prepend do %>
      <%= content_tag(:span, icon(:shopping_cart), :class => 'add-on') %>
      <%= f.input_field :source, :collection => collection %>
    <% end -%>

    <%= f.input :received_at, :wrapper => :prepend, :label => 'Date received' do %>
      <%= content_tag(:span, icon(:calendar), :class => 'add-on') %>
      <%= f.input_field :received_at, 'data-behaviour' => 'datepicker' %>
    <% end -%>

    <%= f.input :address1, :wrapper => :prepend, :label => 'Address Line One' do %>
      <%= content_tag(:span, 1, :class => 'add-on') %>
      <%= f.input_field :address1 %>
    <% end -%>

    <%= f.input :address2, :wrapper => :prepend, :label => 'Address Line Two' do %>
      <%= content_tag(:span, 2, :class => 'add-on') %>
      <%= f.input_field :address2 %>
    <% end -%>

    <%= f.input :city, :wrapper => :prepend do %>
      <%= content_tag(:span, 'C', :class => 'add-on') %>
      <%= f.input_field :city %>
    <% end -%>

    <% collection = PscVariables::STATES.values.map {|state| [ state['name'], state['abbreviation'] ] } %>
    <%= f.input :state, :prompt => 'Please select a state', :wrapper => :prepend do %>
      <%= content_tag(:span, 'S', :class => 'add-on') %>
      <%= f.input_field :state, :collection => collection %>
    <% end -%>

    <%= f.input :zip_code, :wrapper => :prepend, :label => 'Zip Code' do %>
      <%= content_tag(:span, 'Z', :class => 'add-on') %>
      <%= f.input_field :zip_code %>
    <% end -%>
  </div>

  <div class='form-actions'>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing <%= @member.full_name %></h1>

<%= render 'form', :member => @member %>

<% content_for :actions do -%>
  <li><%= link_to 'Show', @member %></li>
  <li><%= link_to 'Destroy', @member, :method => :delete, :data => { :confirm => 'Are you sure?' } %></li>
  <li><%= link_to 'Back', members_path %></li>
<% end -%>

app/views/members/index.html.erb
<h1>Listing members</h1>

<%= form_tag(members_path, :method => 'get', :class => 'form-search') do %>
  <%= search_field_tag(:query, @query, :class => 'input-medium search-query' ) %>
  <%= submit_tag('Search', :class => 'btn' ) %>
<% end %>

<table class='table table-hover table-striped'>
  <thead>
    <tr>
      <th> Name </th>
      <th> Email </th>
    </tr>
  </thead>

  <tbody>
  <% @members.each do |member| %>
    <tr id='<%= element_id(member) -%>'>
      <td><%= link_to member.full_name, member_path(member) %></td>
      <td><%= member.email -%></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br />

<%= paginate @members %>

<% content_for :actions do -%>
  <li><%= link_to 'New Member', new_member_path %></li>
<% end -%>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form', :member => @member %>

<% content_for :actions do -%>
  <li><%= link_to 'Back', members_path %></li>
<% end -%>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for :actions do -%>
  <li><%= link_to 'Edit', edit_member_path(@member) %></li>
  <li><%= link_to 'Back', members_path %></li>
<% end -%>